export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_DATA = 'SET_CURRENT_USER_DATA';

export const FETCH_FORMATIONS_REQUEST = 'FETCH_FORMATIONS_REQUEST';
export const FETCH_FORMATIONS_SUCCESS = 'FETCH_FORMATIONS_SUCCESS';
export const FETCH_FORMATIONS_FAILURE = 'FETCH_FORMATIONS_FAILURE';
export const ADD_FORMATION_SUCCESS = 'ADD_FORMATIONS_REQUEST';
export const ADD_FORMATION_FAILURE = 'ADD_FORMATIONS_REQUEST';
export const EDIT_FORMATION_SUCCESS = 'EDIT_FORMATIONS_SUCCESS';
export const EDIT_FORMATION_FAILURE = 'EDIT_FORMATIONS_SUCCESS';
export const DELETE_FORMATION_SUCCESS = 'EDIT_FORMATIONS_SUCCESS';
export const DELETE_FORMATION_FAILURE = 'DELETE_FORMATIONS_FAILURE';

export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENTS_REQUEST';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENTS_REQUEST';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENTS_SUCCESS';
export const EDIT_STUDENT_FAILURE = 'EDIT_STUDENTS_SUCCESS';
export const DELETE_STUDENT_SUCCESS = 'EDIT_STUDENTS_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENTS_FAILURE';

export const FETCH_TRAINERS_REQUEST = 'FETCH_TRAINERS_REQUEST';
export const FETCH_TRAINERS_SUCCESS = 'FETCH_TRAINERS_SUCCESS';
export const FETCH_TRAINERS_FAILURE = 'FETCH_TRAINERS_FAILURE';
export const ADD_TRAINER_SUCCESS = 'ADD_TRAINERS_REQUEST';
export const ADD_TRAINER_FAILURE = 'ADD_TRAINERS_REQUEST';
export const EDIT_TRAINER_SUCCESS = 'EDIT_TRAINERS_SUCCESS';
export const EDIT_TRAINER_FAILURE = 'EDIT_TRAINERS_SUCCESS';
export const DELETE_TRAINER_SUCCESS = 'EDIT_TRAINERS_SUCCESS';
export const DELETE_TRAINER_FAILURE = 'DELETE_TRAINERS_FAILURE';

export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';
export const ADD_COURSE_SUCCESS = 'ADD_COURSES_REQUEST';
export const ADD_COURSE_FAILURE = 'ADD_COURSES_REQUEST';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSES_SUCCESS';
export const EDIT_COURSE_FAILURE = 'EDIT_COURSES_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'EDIT_COURSES_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSES_FAILURE';
