export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_DATA = 'SET_CURRENT_USER_DATA';

export const FETCH_FORMATIONS_REQUEST = 'FETCH_FORMATIONS_REQUEST';
export const FETCH_FORMATIONS_SUCCESS = 'FETCH_FORMATIONS_SUCCESS';
export const FETCH_FORMATIONS_FAILURE = 'FETCH_FORMATIONS_FAILURE';
export const ADD_FORMATIONS_SUCCESS = 'ADD_FORMATIONS_SUCCESS';
export const ADD_FORMATION_FAILURE = 'ADD_FORMATION_FAILURE';
export const EDIT_FORMATION_SUCCESS = 'EDIT_FORMATION_SUCCESS';
export const EDIT_FORMATION_FAILURE = 'EDIT_FORMATION_FAILURE';
export const DELETE_FORMATION_SUCCESS = 'DELETE_FORMATION_SUCCESS';
export const DELETE_FORMATION_FAILURE = 'DELETE_FORMATION_FAILURE';

export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_FAILURE = 'EDIT_STUDENT_FAILURE';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';

export const FETCH_TRAINERS_REQUEST = 'FETCH_TRAINERS_REQUEST';
export const FETCH_TRAINERS_SUCCESS = 'FETCH_TRAINERS_SUCCESS';
export const FETCH_TRAINERS_FAILURE = 'FETCH_TRAINERS_FAILURE';
export const ADD_TRAINER_SUCCESS = 'ADD_TRAINER_SUCCESS';
export const ADD_TRAINER_FAILURE = 'ADD_TRAINER_FAILURE';
export const EDIT_TRAINER_SUCCESS = 'EDIT_TRAINER_SUCCESS';
export const EDIT_TRAINER_FAILURE = 'EDIT_TRAINER_FAILURE';
export const DELETE_TRAINER_SUCCESS = 'DELETE_TRAINER_SUCCESS';
export const DELETE_TRAINER_FAILURE = 'DELETE_TRAINER_FAILURE';

export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FAILURE';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
export const EDIT_COURSE_FAILURE = 'EDIT_COURSE_FAILURE';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';

export const FETCH_SESSIONS_REQUEST = 'FETCH_SESSIONS_REQUEST';
export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS';
export const FETCH_SESSIONS_FAILURE = 'FETCH_SESSIONS_FAILURE';
export const ADD_SESSION_SUCCESS = 'ADD_SESSION_SUCCESS';
export const ADD_SESSION_FAILURE = 'ADD_SESSION_FAILURE';
<<<<<<< HEAD
export const EDIT_SESSION_SUCCESS = 'EDIT_SESSIONS_SUCCESS';
export const EDIT_SESSION_FAILURE = 'EDIT_SESSIONS_SUCCESS';
export const DELETE_SESSION_SUCCESS = 'EDIT_SESSIONS_SUCCESS';
export const DELETE_SESSION_FAILURE = 'DELETE_SESSIONS_FAILURE';

export const FETCH_CLASSROOMS_REQUEST = 'FETCH_CLASSROOMS_REQUEST';
export const FETCH_CLASSROOMS_SUCCESS = 'FETCH_CLASSROOMS_SUCCESS';
export const FETCH_CLASSROOMS_FAILURE = 'FETCH_CLASSROOMS_FAILURE';
export const ADD_CLASSROOM_REQUEST = 'ADD_CLASSROOM_REQUEST';
export const ADD_CLASSROOM_SUCCESS = 'ADD_CLASSROOM_SUCCESS';
export const ADD_CLASSROOM_FAILURE = 'ADD_CLASSROOM_FAILURE';
export const EDIT_CLASSROOM_SUCCESS = 'EDIT_CLASSROOM_SUCCESS';
export const EDIT_CLASSROOM_FAILURE = 'EDIT_CLASSROOM_SUCCESS';
export const DELETE_CLASSROOM_SUCCESS = 'EDIT_CLASSROOM_SUCCESS';
export const DELETE_CLASSROOM_FAILURE = 'DELETE_CLASSROOM_FAILURE';
=======
export const EDIT_SESSION_SUCCESS = 'EDIT_SESSION_SUCCESS';
export const EDIT_SESSION_FAILURE = 'EDIT_SESSION_FAILURE';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
export const DELETE_SESSION_FAILURE = 'DELETE_SESSION_FAILURE';
>>>>>>> a2d2410f53d995bbec1254afb7f0c82d0b3c6e73
